[package]
name = "cranelift_c_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-codegen = { version = "0.88.1" }
cranelift-module = "0.88.1"
target-lexicon = "0.12.0"
